/*
-- Find consecutive free seats
CREATE TABLE CINEMA_TBL (SEAT_ID INT, FREE INT)

INSERT INTO CINEMA_TBL VALUES (1,1);
INSERT INTO CINEMA_TBL VALUES(2,0);
INSERT INTO CINEMA_TBL VALUES (3,1);
INSERT INTO CINEMA_TBL VALUES (4,0);
INSERT INTO CINEMA_TBL VALUES (5,1);
INSERT INTO CINEMA_TBL VALUES (6,1);
INSERT INTO CINEMA_TBL VALUES (7,1);
INSERT INTO CINEMA_TBL VALUES (8,0);
INSERT INTO CINEMA_TBL VALUES (9,1);
INSERT INTO CINEMA_TBL VALUES (10,1);
*/
WITH SEQUENCE_SEAT
  AS (SELECT *,
             COUNT(*) OVER (PARTITION BY FREE, RNK) AS FILTER
        FROM (   SELECT *,
                        SEAT_ID - ROW_NUMBER() OVER (PARTITION BY FREE ORDER BY SEAT_ID ASC) AS RNK
                   FROM CINEMA_TBL) SEQ )
SELECT SEAT_ID
  FROM SEQUENCE_SEAT
 WHERE FILTER > 1;


WITH SEAT_DATA
  AS (SELECT *,
             LAG(FREE) OVER (ORDER BY SEAT_ID) AS PREV_SEAT,
             LEAD(FREE) OVER (ORDER BY SEAT_ID) AS NEXT_SEAT
        FROM CINEMA_TBL)
SELECT SEAT_ID
  FROM SEAT_DATA
 WHERE PREV_SEAT = FREE
    OR NEXT_SEAT = FREE;