-- Given match result generate match table which has team,won match,lost match,total match
/*
CREATE TABLE ICC_WORLD_CUP
(
TEAM_1 VARCHAR(20),
TEAM_2 VARCHAR(20),
WINNER VARCHAR(20)
);
INSERT INTO ICC_WORLD_CUP VALUES('INDIA','SL','INDIA');
INSERT INTO ICC_WORLD_CUP VALUES('SL','AUS','AUS');
INSERT INTO ICC_WORLD_CUP VALUES('SA','ENG','ENG');
INSERT INTO ICC_WORLD_CUP VALUES('ENG','NZ','NZ');
INSERT INTO ICC_WORLD_CUP VALUES('AUS','INDIA','INDIA');
*/

WITH TEAMS
     AS (SELECT TEAM_1 AS TEAM,WINNER FROM ICC_WORLD_CUP
         UNION ALL
         SELECT TEAM_2 AS TEAM,WINNER FROM ICC_WORLD_CUP)
SELECT TEAM,
       COUNT(*) AS MATCHES_PLAYED,
       SUM(CASE WHEN WINNER = TEAM THEN 1 ELSE 0 END) AS MATCHES_WON,
       SUM(CASE WHEN WINNER <> TEAM THEN 1 ELSE 0 END) AS MATCHES_LOSS
FROM   TEAMS
GROUP  BY TEAM;