/*
Find most popular based on search
CREATE TABLE AIRBNB_SEARCHES
(
USER_ID INT,
DATE_SEARCHED DATE,
FILTER_ROOM_TYPES VARCHAR(200)
);

INSERT INTO AIRBNB_SEARCHES VALUES
(1,'2022-01-01','ENTIRE HOME,PRIVATE ROOM'),
(2,'2022-01-02','ENTIRE HOME,SHARED ROOM'),
(3,'2022-01-02','PRIVATE ROOM,SHARED ROOM'),
(4,'2022-01-03','PRIVATE ROOM');
*/

WITH DATA AS (
SELECT
SUM (CASE WHEN "FILTER_ROOM_TYPES" LIKE '%ENTIRE HOME%' THEN 1 ELSE 0 END) AS ENTIRE_HOME_COUNT ,
SUM (CASE WHEN "FILTER_ROOM_TYPES" LIKE '%PRIVATE ROOM%' THEN 1 ELSE 0 END )AS PRIVATE_ROOM_COUNT ,
SUM (CASE WHEN "FILTER_ROOM_TYPES" LIKE '%SHARED ROOM%' THEN 1 ELSE 0 END) AS SHARED_ROOM_COUNT
FROM dbo.AIRBNB_SEARCHES
)
SELECT 'ENTIRE HOME' AS ROOM_TYPE ,ENTIRE_HOME_COUNT FROM DATA
UNION
SELECT 'PRIVATE ROOM' AS ROOM_TYPE ,PRIVATE_ROOM_COUNT FROM DATA
UNION
SELECT 'SHARED ROOM' AS ROOM_TYPE ,SHARED_ROOM_COUNT FROM DATA;