-- We need to find player with no of gold medals won by them only for players who won only gold medals.
/*
CREATE TABLE EVENTS (
ID INT,
EVENT VARCHAR(255),
YEAR INT,
GOLD VARCHAR(255),
SILVER VARCHAR(255),
BRONZE VARCHAR(255)
);

INSERT INTO EVENTS VALUES (1,'100M',2016, 'AMTHHEW MCGARRAY','DONALD','BARBARA');
INSERT INTO EVENTS VALUES (2,'200M',2016, 'NICHOLE','ALVARO EATON','JANET SMITH');
INSERT INTO EVENTS VALUES (3,'500M',2016, 'CHARLES','NICHOLE','SUSANA');
INSERT INTO EVENTS VALUES (4,'100M',2016, 'RONALD','MARIA','PAULA');
INSERT INTO EVENTS VALUES (5,'200M',2016, 'ALFRED','CAROL','STEVEN');
INSERT INTO EVENTS VALUES (6,'500M',2016, 'NICHOLE','ALFRED','BRANDON');
INSERT INTO EVENTS VALUES (7,'100M',2016, 'CHARLES','DENNIS','SUSANA');
INSERT INTO EVENTS VALUES (8,'200M',2016, 'THOMAS','DAWN','CATHERINE');
INSERT INTO EVENTS VALUES (9,'500M',2016, 'THOMAS','DENNIS','PAULA');
INSERT INTO EVENTS VALUES (10,'100M',2016, 'CHARLES','DENNIS','SUSANA');
INSERT INTO EVENTS VALUES (11,'200M',2016, 'JESSICA','DONALD','STEFENEY');
INSERT INTO EVENTS VALUES (12,'500M',2016,'THOMAS','STEVEN','CATHERINE');
*/
SELECT * FROM   DBO.EVENTS;
SELECT GOLD AS NAME,
       COUNT(*) AS NUMBER_OF_GOLD
FROM   DBO.EVENTS
WHERE  GOLD NOT IN (SELECT DISTINCT SILVER FROM  DBO.EVENTS)
       AND GOLD NOT IN (SELECT DISTINCT BRONZE FROM  DBO.EVENTS)
GROUP  BY GOLD;