/*
-- Find users who only bought i phone 15
CREATE TABLE IPHONE (USR_ID INT, IPHONE_MODEL INT);

INSERT INTO IPHONE VALUES (1,11);
INSERT INTO IPHONE VALUES (1,11);
INSERT INTO IPHONE VALUES (2,15);
INSERT INTO IPHONE VALUES (3,11);
INSERT INTO IPHONE VALUES (3,15);
INSERT INTO IPHONE VALUES (3,15);
INSERT INTO IPHONE VALUES (4,15);
*/
WITH CTE AS (SELECT *, CASE WHEN IPHONE_MODEL=15 THEN 0 ELSE 1 END AS IPHONE15_FLAG
             FROM IPHONE)
SELECT USR_ID FROM CTE GROUP BY USR_ID HAVING SUM(IPHONE15_FLAG)=0;