/*
Remove records which are duplicate when values reversed in columns.
Input
---------
A	B
1	2
3	2
2	4
2	1
5	6
4	2
---------
Output
A	B
1	2
3	2
2	4
5	6
*/

CREATE TABLE IF NOT EXISTS DUPLICATE_PAIR (`A` INTEGER , `B` INTEGER);
INSERT INTO DUPLICATE_PAIR VALUES (1,2);
INSERT INTO DUPLICATE_PAIR VALUES (3,2);
INSERT INTO DUPLICATE_PAIR VALUES (2,4);
INSERT INTO DUPLICATE_PAIR VALUES (2,1);
INSERT INTO DUPLICATE_PAIR VALUES (5,6);
INSERT INTO DUPLICATE_PAIR VALUES (4,2);

SELECT A,B
FROM   (SELECT A,B,ROW_NUMBER() OVER(PARTITION BY A_B ORDER BY A_B) AS ROW_NUM
        FROM   (SELECT A,B,CASE WHEN A < B THEN CONCAT(A, "_", B) ELSE CONCAT(B, '_', A) END AS A_B
                FROM   DUPLICATE_PAIR) FINAL) FINAL
WHERE  ROW_NUM = 1;