/*
CREATE TABLE  TRIPS (ID INT, CLIENT_ID INT, DRIVER_ID INT, CITY_ID INT, STATUS VARCHAR(50), REQUEST_AT VARCHAR(50));
CREATE TABLE USER_DETAILS (USERS_ID INT, BANNED VARCHAR(50), ROLE VARCHAR(50));
TRUNCATE TABLE TRIPS;
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('1', '1', '10', '1', 'COMPLETED', '2013-10-01');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('2', '2', '11', '1', 'CANCELLED_BY_DRIVER', '2013-10-01');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('3', '3', '12', '6', 'COMPLETED', '2013-10-01');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('4', '4', '13', '6', 'CANCELLED_BY_CLIENT', '2013-10-01');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('5', '1', '10', '1', 'COMPLETED', '2013-10-02');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('6', '2', '11', '6', 'COMPLETED', '2013-10-02');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('7', '3', '12', '6', 'COMPLETED', '2013-10-02');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('8', '2', '12', '12', 'COMPLETED', '2013-10-03');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('9', '3', '10', '12', 'COMPLETED', '2013-10-03');
INSERT INTO TRIPS (ID, CLIENT_ID, DRIVER_ID, CITY_ID, STATUS, REQUEST_AT) VALUES ('10', '4', '13', '12', 'CANCELLED_BY_DRIVER', '2013-10-03');
TRUNCATE TABLE USER_DETAILS;
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('1', 'NO', 'CLIENT');
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('2', 'YES', 'CLIENT');
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('3', 'NO', 'CLIENT');
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('4', 'NO', 'CLIENT');
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('10', 'NO', 'DRIVER');
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('11', 'NO', 'DRIVER');
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('12', 'NO', 'DRIVER');
INSERT INTO USER_DETAILS (USERS_ID, BANNED, ROLE) VALUES ('13', 'NO', 'DRIVER');
*/
-- Find the cancellation report on daily basis with for active users
SELECT *, CANCELLED_TRIP * 100 / TOTAL_TRIP AS CANCEL_PERCENT
FROM(SELECT REQUEST_AT, COUNT(*) AS TOTAL_TRIP, SUM(CASE WHEN STATUS IN ('CANCELLED_BY_CLIENT', 'CANCELLED_BY_DRIVER') THEN 1 ELSE 0 END) AS CANCELLED_TRIP
     FROM TRIPS T
          LEFT OUTER JOIN USER_DETAILS C ON T.CLIENT_ID=C.USERS_ID AND C.BANNED='NO' AND C.ROLE='CLIENT'
          LEFT OUTER JOIN USER_DETAILS D ON T.DRIVER_ID=D.USERS_ID AND D.BANNED='NO' AND D.ROLE='DRIVER'
     WHERE C.USERS_ID IS NOT NULL AND D.USERS_ID IS NOT NULL
     GROUP BY REQUEST_AT)DATA
